# Generated by Django 5.0.2 on 2024-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('penyewaan_id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_sewa', models.DateField(db_column='TanggalSewa')),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'penyewaan',
                'managed': False,
            },
        ),
    ]
