# Generated by Django 5.0.2 on 2024-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobil',
            fields=[
                ('mobil_id', models.AutoField(primary_key=True, serialize=False)),
                ('merek', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('tahun', models.IntegerField()),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Sedang Disewa', 'Sedang Disewa')], max_length=13)),
            ],
            options={
                'db_table': 'mobil',
                'managed': False,
            },
        ),
    ]
